version: "3"

services:
  db:
    build: "./egg-coder-db"
    ports:
      - "3366:3306"
    volumes:
      - ./egg-coder-db/conf.d:/etc/mysql/conf.d
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_DATABASE=egg_coder
      - MYSQL_PORT=3306
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin@123
      - MYSQL_ROOT_PASSWORD=root@123
    container_name: egg-coder-db

  db-test:
    build:
      context: ./egg-coder-db
      dockerfile: Dockerfile.test
    ports:
      - "3367:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_DATABASE=egg_coder
      - MYSQL_PORT=3306
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin@123
      - MYSQL_ROOT_PASSWORD=root@123
    container_name: egg-coder-db-test
