version: "3"

services:
  db:
    build: "./egg-coder-db"
    ports:
      - "3366:3306"
    volumes:
      - ./egg-coder-db/conf.d:/etc/mysql/conf.d
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_DATABASE=EGG_CODER
      - MYSQL_PORT=3306
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin@123
      - MYSQL_ROOT_PASSWORD=root@123
    container_name: egg-coder-db

  db-test:
    image: mysql:8.0
    ports:
      - "3367:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_DATABASE=EGG_CODER
      - MYSQL_PORT=3306
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin@123
      - MYSQL_ROOT_PASSWORD=root@123
    container_name: egg-coder-db-test

#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    links:
#      - db:mysql
#    ports:
#      - "9196:80"
#    environment:
#      PMA_HOST: db
#      PMA_PORT: 3306
#      PMA_USER: admin
#      PMA_PASSWORD: admin@123
#    container_name: luuk-phpmyadmin
