SET GLOBAL time_zone = "Asia/Tokyo";

-- --------------------------------------------------------

--
-- Table structure for database(EGG_CODER)
--

DROP DATABASE IF EXISTS EGG_CODER;
CREATE DATABASE EGG_CODER
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;
SET default_storage_engine = InnoDB;

USE EGG_CODER;

-- ユーザー
CREATE TABLE `USER`
(
    `ID_USER`        VARCHAR(50)  NOT NULL PRIMARY KEY,
    `NAME`           VARCHAR(255) NOT NULL,
    `CREATED_AT`     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `CREATED_BY`     VARCHAR(255) NOT NULL,
    `UPDATED_AT`     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_BY`     VARCHAR(255) NOT NULL,
    `DELETED_AT`     TIMESTAMP             DEFAULT NULL
);

-- 記録
CREATE TABLE `RECORD`
(
    `ID_RECORD`      VARCHAR(50)    NOT NULL PRIMARY KEY,
    `TITLE`          VARCHAR(255)   NOT NULL,
    `QUESTION`       TEXT           NOT NULL,
    `USER_ANSWER`    TEXT           NOT NULL,
    `MODEL_ANSWER`   TEXT           NOT NULL,
    `REVIEW_FLAG`    TINYINT(1)     NOT NULL DEFAULT 0,
    `CREATED_AT`     TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `CREATED_BY`     VARCHAR(255)   NOT NULL,
    `UPDATED_AT`     TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_BY`     VARCHAR(255)   NOT NULL,
    `DELETED_AT`     TIMESTAMP               DEFAULT NULL
);

-- タグ
CREATE TABLE `TAG`
(
    `ID_TAG`         VARCHAR(50)    NOT NULL PRIMARY KEY,
    `ID_USER`        VARCHAR(50)    NOT NULL,
    `NAME`           VARCHAR(255)   NOT NULL,
    `COLOR_CODE`     VARCHAR(6)     NOT NULL,
    `CREATED_AT`     TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `CREATED_BY`     VARCHAR(255)   NOT NULL,
    `UPDATED_AT`     TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_BY`     VARCHAR(255)   NOT NULL,
    `DELETED_AT`     TIMESTAMP               DEFAULT NULL,
    UNIQUE  KEY `UK01_TAG` (`ID_USER`),
    FOREIGN KEY `FK01_TAG` (`ID_USER`) REFERENCES `EGG_CODER`.`USER` (`ID_USER`)
);

-- タグと記録のマッピングテーブル
CREATE TABLE `TAG_RECORD`
(
    `ID_RECORD`      VARCHAR(50)    NOT NULL,
    `ID_TAG_JSON`    JSON           NOT NULL,
    `CREATED_AT`     TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `CREATED_BY`     VARCHAR(255)   NOT NULL,
    `UPDATED_AT`     TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_BY`     VARCHAR(255)   NOT NULL,
    `DELETED_AT`     TIMESTAMP               DEFAULT NULL,
    UNIQUE  KEY `UK01_TAG` (`ID_RECORD`),
    FOREIGN KEY `FK01_TAG` (`ID_RECORD`) REFERENCES `EGG_CODER`.`RECORD` (`ID_RECORD`)
);

-- ログイン情報
CREATE TABLE `LOGIN_AUTHORITY`
(
    `ID_LOGIN_AUTHORITY`   VARCHAR(50)    NOT NULL PRIMARY KEY,
    `ID_USER`              VARCHAR(50)    NOT NULL,
    `EMAIL`                VARCHAR(100)   NOT NULL,
    `PASSWORD`             VARCHAR(100)   NOT NULL,
    `CREATED_AT`           TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `CREATED_BY`           VARCHAR(255)   NOT NULL,
    `UPDATED_AT`           TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_BY`           VARCHAR(255)   NOT NULL,
    `DELETED_AT`           TIMESTAMP               DEFAULT NULL,
    UNIQUE  KEY `UK01_TAG` (`ID_USER`),
    FOREIGN KEY `FK01_TAG` (`ID_USER`) REFERENCES `EGG_CODER`.`USER` (`ID_USER`)
);

