SET CHARSET UTF8;

INSERT INTO EGG_CODER.USER(`ID_USER`,
                        `USER_TYPE_CODE`,
                        `NAME`,
                        `DISPLAY_NAME`,
                        `EMAIL`,
                        `CREATED_BY`,
                        `UPDATED_BY`)
VALUES (1,
        2,
        'スタンダードプランユーザ',
        'きょーすけ',
        'Manager1@com',
        'INITIAL',
        'INITIAL'),
       (2,
        2,
        'プロプラン本校ユーザ',
        'ZEEBRA',
        'Manager2@com',
        'INITIAL',
        'INITIAL'),
       (3,
        1,
        '管理者',
        'admin1',
        'admin@lacicu.co.jp',
        'INITIAL',
        'INITIAL'),
       (4,
        2,
        'プロプラン下部教室ユーザ',
        'Jukuma',
        'Manager3@com',
        'INITIAL',
        'INITIAL'),
       (5,
        2,
        'ミウラテスト用',
        'EAST',
        'Manager4@com',
        'INITIAL',
        'INITIAL');
