spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver

#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html

#  mvc:
#    static-path-pattern: /resources/**

server:
  port: 8080
  servlet:
    session:
      timeout: 86400

mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: # Add path to mappers
    #    - classpath:/mybatis/mapper/*.xml
    - classpath:/mybatis/mapper/*.xml